### ISSUE TITLE
Not an issue - love the plugin :)

### ISSUE THREAD

**Issue by daviddarke** [Fabianlindfors/advanced-forms#1]
Hi, love the concept. If you need a hand with feature development etc just shout. Going to roll it out on a couple of sites soon.

**Comment by Fabianlindfors** [comment]
Great to hear, thanks a lot!

Please report any bugs you find, would love the feedback. Also feel free to make a feature request if you're missing something from the plugin. :)

**Comment by daviddarke** [comment]
Will do! :)
